### ISSUE TITLE
[BUG] Mod not loading

### ISSUE THREAD

**Issue by FiveEYZ** [CodenameRevy/-1.14.4-MagicMirror#4]
**Describe the bug**
Used twitch client to install the mod for 1.15.2but it complains to only work for 1.15.1
https://gist.github.com/FiveEYZ/4c7c92e79fba201ec88788f2bb75c7b2

**To Reproduce**
install latest version for 1.15.2 currently on curseforge

**Desktop OS and Java Version (please complete the following information):**
 - OS: windows 10
 - Version: 1.0.4.4
 - Java Version: 1.8.0_241

**Mods installed:**
Just Enough Items (JEI) (by mezz)
Light Overlay (Rift/Forge/Fabric) (by shedaniel)
Gauges and Switches (by wilechaote)
Mystical Agradditions (by BlakeBr0)
Engineer's Decor (by wilechaote)
PackMenu (by Shadows_of_Fire)
ReAuth (by TechnicianLP)
Cucumber Library (by BlakeBr0)
Dungeon Crawl (by XIROC1337)
Bonsai Trees 2 (by davenonymous)
Cloth Config API (Forge) (by shedaniel)
Xaero's World Map (by xaero96)
The One Probe (by McJty)
Bow Infinity Fix (by Parker8283)
U Team Core (by HyCraftHD)
Trample Stopper (by UnRealDinnerbone)
SwingThroughGrass (by exidex)
Biomes O' Plenty (by Forstride)
Mystical Agriculture (by BlakeBr0)
Useful Railroads (by HyCraftHD)
Blue Power (by Quetzi)
Time Travel Mod (by rdvdev2)
Apotheosis (by Shadows_of_Fire)
Water Strainer (by Ruuubi)
XL Food Mod (by mariot7)
Expanded Storage (by NinjaPhenix)
OpenBlocks Elevator (by vsngarcia)
Mekanism (by bradyaidanc)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
Miner's Helmet (by ModdingLegacy)
Magic Mirrors (by CodenameRevy)
Parachute Mod (by pbrane0)
More Charcoal (by al132)
Inventory Sorter (by cpw)
Macaw's Bridges (by sketch_macaw)
Backpacked (by MrCrayfish)
Lava Monsters (by ModdingLegacy)
Corail Tombstone (by Corail_31)
Libnonymous (by davenonymous)
Fast Leaf Decay (by olafskiii)
Curios API (by TheIllusiveC4)
Torch Slabs Mod (by EndlesNights)
Falling Tree (by RakSrinaNa)
Controlling (by Jaredlll08)
Nethercraft Classic (by ModdingLegacy)
Xaero's Minimap (by xaero96)
Placebo (by Shadows_of_Fire)

**Additional context**
https://github.com/CodenameRevy/MagicMirrors/blob/2baee2c91cc03a775ef3fac2698373c0376f90b9/src/main/resources/META-INF/mods.toml#L27

META-INF/mods.toml needs to be updated for 1.15.2

**Comment by mdujovic17** [comment]
Fixed in 1.0.4.5...
