### ISSUE TITLE
Reduce the particle animation radius when teleporting

### ISSUE THREAD

**Issue by TheDirectorX** [CodenameRevy/-1.14.4-MagicMirror#9]
**Is your feature request related to a problem?**
It seems to me that the animation of particles during teleportation is very scattered.

**Describe the solution you'd like**
I want the particles to be more focused on the player (reduce the particle radius to about **0.5–0.75** block from the player in all cardinal direction [_north, east, south, west_])

**Additional context**
![2020-04-06_01 33 17](https://user-images.githubusercontent.com/43481085/78509569-4be91900-77a8-11ea-9017-d29041748c0e.png)

**Comment by mdujovic17** [comment]
I'll consider it. I will do some testing to see how it looks with different values.

**Comment by mdujovic17** [comment]
Reduced radius to 0.5.

**Comment by TheDirectorX** [comment]
@CodenameRevy Yo! On Curse, there is a non-working link to my [GitHub profile](https://github.com/TheDirectorX).
_I will delete this message after you read/correct it._

**Comment by mdujovic17** [comment]
CurseForge doesn't like links without https in them lol. Fixed it.
